name: Release

on:
  push:
    branches:
      - "master"
    paths:
      - ".version"

jobs:
  run_tests:
    name: Publish release
    runs-on: macos-15
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"
      - name: "Fetch source"
        env:
          SRC_URL: "github.com/passepartoutvpn/passepartoutkit-source"
        run: |
          git clone https://git:${{ secrets.ACCESS_TOKEN }}@$SRC_URL src
      - uses: passepartoutvpn/action-release-binary-package@master
        with:
          script: "ci-generate.sh"
          framework: "PassepartoutKit.xcframework"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          prerelease: true
